<?php
/**
 * @file
 * Code for the Google Store Locator feature.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Config\Config;

/**
 * Implements hook_theme().
 */
function google_store_locator_theme() {
  // Returns an associative array of theme hook information.
  return [
    // The outer array keys are the names of the theme functions, and the values
    // are arrays containing information about the hook.
    'google_store_locator' => [
      // Keys=names of the variables passed to the themable function,
      // value=default value of the variable if none is provided.
      'variables' => [
        'settings' => [
          'data_path' => NULL,
          'map_zoom' => NULL,
          'map_cluster' => NULL,
          'map_cluster_grid' => NULL,
          'map_cluster_zoom' => NULL,
          'map_cluster_image_path' => NULL,
          'map_style' => NULL,
          'viewport_manage' => NULL,
          'viewport_marker_limit' => NULL,
          'map_long' => NULL,
          'map_lat' => NULL,
          'items_per_panel' => NULL,
          'loc_search_zoom' => NULL,
          'loc_aware' => NULL,
          'loc_aware_zoom' => NULL,
          'search_label' => NULL,
          'search_placeholder' => NULL,
          'no_results' => NULL,
          'marker_path' => NULL,
          'feature_list' => NULL,
          'link_target' => NULL,
        ]
      ],
    ],
  ];
}

/**
 * Default implementation of the google_store_locator theme hook.
 *
 * Builds the renderable array that attaches all necessary js files to the head
 * section of the page and generates the map and panel elements.
 */
function template_preprocess_google_store_locator(&$variables) {
  $gslSettings = \Drupal\google_store_locator\Util::getGlobalSettings();
  // Expand settings with defaults.
  $settings = $variables['settings'] + \Drupal\google_store_locator\Util::getDefaultSettings($gslSettings);

  $library = 'google_store_locator/google_store_locator';
  // Switch to the location awareness library if enabled.
  if (!empty($gslSettings->get('loc_aware'))) {
    $library = 'google_store_locator/google_store_locator_loc_aware';
  }
  // Add the google maps library.
  $mapsLibrary = 'google_store_locator/libraries.googlemaps';
  if ($gslSettings->get('gsl_lang_aware')) {
    $mapsLibrary .= '-' . \Drupal::languageManager()->getCurrentLanguage()->getId();
  }
  $gsl_map_id = \Drupal\Component\Utility\Html::getUniqueId(
    'google-store-locator-map-container'
  );
  $variables['attributes'] += ['id' => $gsl_map_id, 'class' => 'google-store-locator-map-container'];
  $variables += [
    '#attached' => [
      'library' => [$mapsLibrary, $library],
      'drupalSettings' => [
        'gsl' => [
          $gsl_map_id => $settings,
          'proximity' => $gslSettings->get('proximity_enabled'),
          'metric' => $gslSettings->get('proximity_metric'),
          'display_search_marker' => $gslSettings->get(
            'gsl_display_search_marker'
          ),
          'max_zoom' => $gslSettings->get('gsl_max_zoom'),
        ],
      ],
    ],
    'gsl_panel' => [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => ['id' => $gsl_map_id . '-panel', 'class' => 'google-store-locator-panel'],
    ],
    'gsl_map' => [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => ['id' => $gsl_map_id . '-map', 'class' => 'google-store-locator-map'],
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function google_store_locator_library_info_build() {
  $libraries = [];

  /** @var \Drupal\Core\Config\ConfigFactory $config */
  $config = \Drupal::service('config.factory');
  /** @var \Drupal\Core\Config\Config|\Drupal\Core\Config\ImmutableConfig $gslSettings */
  $gslSettings = $config->get('google_store_locator.settings');

  $libraries['libraries.googlemaps'] = [
    'js' => [
      '//maps.googleapis.com/maps/api/js?key=' . $gslSettings->get(
        'google_api_key'
      ) . '&libraries=places' => [
        'type' => 'external',
        'group' => JS_LIBRARY,
        'weight' => -100,
        'attributes' => [
          'defer' => TRUE,
          'async' => TRUE,
        ],
      ],
    ],
  ];
  // Register a library for each enabled language - can't think of any other way
  // to do this with the current libraries implementation.
  foreach (\Drupal::languageManager()->getLanguages() as $language) {
    $libraries['libraries.googlemaps-' . $language->getId()] = $libraries['libraries.googlemaps'];
    $js = key($libraries['libraries.googlemaps']['js']);
    $libraries['libraries.googlemaps-' . $language->getId()]['js'][$js . '&language=' . $language->getId()] = $libraries['libraries.googlemaps-' . $language->getId()]['js'][$js];
    unset($libraries['libraries.googlemaps-' . $language->getId()]['js'][$js]);
  }

  return $libraries;
}

/**
 * Submit callback for google_store_locator_admin_form.
 */
function google_store_locator_admin_form_submit($form, &$form_state) {
  if ($form['google_store_locator']['gsl_marker_icon']['#default_value'] != 0) {
    if ($form['google_store_locator']['gsl_marker_icon']['#default_value'] != $form_state['values']['gsl_marker_icon']) {
      $old_file = file_load(
        $form['google_store_locator']['gsl_marker_icon']['#default_value']
      );
      file_delete($old_file);
    }
  }
  if ($form_state['values']['gsl_marker_icon'] != 0) {
    // Load the file via file.fid.
    $file = file_load($form_state['values']['gsl_marker_icon']);
    // Change status to permanent.
    $file->status = FILE_STATUS_PERMANENT;
    // Save.
    file_save($file);
    file_usage_add(
      $file,
      'google_store_locator',
      'google_store_locator',
      $file->fid
    );
  }
  menu_rebuild();
}

/**
 * Implements hook_help().
 */
function google_store_locator_help(
  $route_name,
  \Drupal\Core\Routing\RouteMatchInterface $route_match
) {
  $content = '';
  switch ($route_name) {
    case 'help.page.google_store_locator':
      $t_args = [];
      $content .= '<h3>' . t('Configuration: Libraries: Help') . '</h3>';
      $content .= '<p>' . t('The Google Store Locator module utilizes third-party Open Source libraries to enhance functionality.') . ' ' .
        t('It is recommended that these libraries are installed in your Drupal installations <code>/libraries</code> directory.') . ' ' .
        '</p>' .
        '<p>' . t('There are several ways to download the needed third-party libraries.') . '</p>' .
        '<p><strong>' . t('Recommended') . '</strong></p>' .
        '<ul>' .
        '  <li>' . t('Use the <a href="https://github.com/wikimedia/composer-merge-plugin">Composer Merge plugin</a> to include the Google Store Locator module\'s <a href="https://cgit.drupalcode.org/google_store_locator/tree/composer.libraries.json">composer.libraries.json</a>.', $t_args) . '<br/>You can use the same approach as for Webform: <strong>' . t('<a href="https://www.drupal.org/node/3003140">Learn more &raquo;</a>') . '</strong>'. '</li>' .
        '</ul>';
  }
  return $content;
}
